%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 600
image_height: 264
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 300
   fy: 300
   cx: 300
   cy: 132